[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gha_pypi_release_test"
description = "A test package for figuring out how GitHub Actions releases should work."
version = "1.0.0"

[dependency-groups]
tests = [
    "tox",
]
