---
permissions: {}

on:
  release:
    types: [ "created" ]

jobs:
  checks:
    permissions:
      contents: "read"
    uses: "./.github/workflows/checks.yaml"

  publish:
    permissions:
      contents: "write"
      id-token: "write"
    uses: "./.github/workflows/publish.yaml"
    needs: [ "checks" ]
...
