---
name: "test"

permissions: {}

on:
  workflow_call:

jobs:
  test:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871"  # v4.2.1
        with:
          persist-credentials: false

      - uses: "astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086"  # v3.1.5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: "Run tests"
        run: >
          uv tool run
          --python '${{ matrix.python-version }}'
          --with tox-uv
          tox run -e coverage-clean,py,coverage-report
...
